name: simpeg-mt
channels:
  - conda-forge
dependencies:
  - python=3.11

  # Core scientific stack
  - numpy
  - scipy
  - matplotlib

  # Discretization & inversion
  - discretize
  - simpeg

  # Solvers
  - pymatsolver
  - pydiso
  - mkl  # improves Pardiso performance

  # Utilities
  - utm
  - h5py
  - pyproj
  - geopy
  - geopandas
  - openssl=3.6.2

  # Optional but useful
  - jupyterlab
  - ipython

  # Metadata handling
  - pip
  - pip:
      - mtpy-v2
      - mt-metadata
      - mth5